# Generated by Django 5.2.7 on 2025-10-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('is_doctor', models.BooleanField(default=False)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
