# Generated by Django 5.2.7 on 2025-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='occupation',
        ),
        migrations.AddField(
            model_name='contact',
            name='occupation_category',
            field=models.CharField(blank=True, db_column='occupation_category', max_length=255, null=True, verbose_name='Occupation Category'),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postion/Organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile_image',
            field=models.ImageField(blank=True, default='user_images/default.png', null=True, upload_to='user_images/'),
        ),
    ]
