# Generated by Django 5.2.7 on 2025-10-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_options_remove_contact_is_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postion and Organization/Company'),
        ),
    ]
