# Generated by Django 5.2.7 on 2025-10-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_doctor', models.BooleanField(default=False, verbose_name='Is a Doctor?')),
                ('occupation', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Social Worker', 'Social Worker'), ('Doctor', 'Doctor'), ('Entrepreneur', 'Entrepreneur'), ('Other', 'Other - Specify')], max_length=255, null=True)),
                ('occupation_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specify Other Occupation')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company/Organization')),
                ('profile_image', models.ImageField(blank=True, default='user_images/default.png', null=True, upload_to='user_images/')),
                ('occupation_category', models.ForeignKey(blank=True, db_column='occupation_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jobcategory', verbose_name='Occupation Category')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
