# Generated by Django 5.2.7 on 2025-10-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='members',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='members',
            name='occupation_other',
        ),
        migrations.AddField(
            model_name='members',
            name='Position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
