# Generated by Django 5.2.7 on 2025-10-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_members_is_doctor_remove_members_occupation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='Position',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='members',
            name='occupation_category',
            field=models.ForeignKey(blank=True, db_column='occupation_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jobcategory', verbose_name='position Category'),
        ),
    ]
