# Generated by Django 5.2.7 on 2025-10-31 10:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='banner',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='blog_media/', validators=[blog.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
